"""
report_generator.py
Structured audit report export for EcoPulse.
Generates both plain-text preview and a proper PDF.
Uses fpdf2 (FPDF2) — install with:  pip install fpdf2
"""

import io
import textwrap
from datetime import datetime

import pandas as pd

try:
    from fpdf import FPDF  # fpdf2
    _FPDF_AVAILABLE = True
except ImportError:
    _FPDF_AVAILABLE = False


DISCLAIMER = (
    "SIMULATION DISCLAIMER: All sensor readings, health scores, energy figures, "
    "and financial estimates in this report are generated by a physics-inspired "
    "simulator. No real plant or machinery data has been used. Efficiency class "
    "labels are illustrative, based on IS 12615 / IEC 60034-30-1 thresholds. "
    "This report is produced for demonstration purposes only."
)

STANDARDS_NOTE = (
    "Methodology: Sensor data is generated by a correlated simulator (current driven "
    "by a shift load profile; temperature via first-order thermal lag on current; "
    "vibration load- and fault-dependent). Vibration severity zones follow ISO 10816-3. "
    "Motor ratings follow standard 415 V three-phase values (7.5 / 15 / 30 kW). "
    "Efficiency classes follow IS 12615 / IEC 60034-30-1. Energy-audit structure is "
    "aligned with BEE guidance notes. No real plant data is used."
)


class AuditReportGenerator:
    def __init__(
        self,
        asset_name: str,
        audit_data: dict,
        telemetry_df: pd.DataFrame,
        efficiency_class: dict | None = None,
        fault_diagnosis: list[dict] | None = None,
        rul_data: dict | None = None,
        fleet_summary: dict | None = None,
    ):
        self.asset_name       = asset_name
        self.audit_data       = audit_data
        self.telemetry_df     = telemetry_df
        self.efficiency_class = efficiency_class or {}
        self.fault_diagnosis  = fault_diagnosis or []
        self.rul_data         = rul_data or {}
        self.fleet_summary    = fleet_summary or {}
        self.generated_at     = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    # ------------------------------------------------------------------
    # Plain-text preview
    # ------------------------------------------------------------------
    def generate_text_report(self) -> str:
        df  = self.telemetry_df
        ad  = self.audit_data
        ec  = self.efficiency_class
        rul = self.rul_data
        fs  = self.fleet_summary

        anomaly_count = int(df["is_anomaly"].sum()) if "is_anomaly" in df.columns else 0
        avg_health    = df["health_score_%"].mean() if "health_score_%" in df.columns else "N/A"

        lines = [
            "=" * 80,
            "          ECOPULSE  —  ENERGY & PREDICTIVE MAINTENANCE AUDIT REPORT",
            "=" * 80,
            f"Generated On        : {self.generated_at}",
            f"Asset               : {self.asset_name}",
            f"Standards Cited     : ISO 10816-3 | IS 12615 | IEC 60034-30-1 | BEE Guidance",
            "",
            "-" * 80,
            "SECTION 1 — EXECUTIVE SUMMARY",
            "-" * 80,
            f"Fleet avg health            : {avg_health:.1f} %  (100 = perfect; <50 = critical)",
            f"Anomaly events detected     : {anomaly_count}",
            f"Annual energy savings est.  : {ad.get('kwh_saved_yr', 0):,.0f} kWh / year",
            f"Annual cost savings est.    : ₹{ad.get('inr_saved_yr', 0):,.0f} / year",
            f"Estimated payback           : {fs.get('payback_months', '—')} months",
            "",
            "-" * 80,
            "SECTION 2 — SCOPE AND METHOD",
            "-" * 80,
        ]
        for line in textwrap.wrap(STANDARDS_NOTE, width=78):
            lines.append(line)

        lines += [
            "",
            "-" * 80,
            "SECTION 3 — FINDINGS (ASSET TELEMETRY)",
            "-" * 80,
            f"Observations              : {len(df)} samples",
            f"Avg active power          : {df['active_power_kw'].mean():.2f} kW",
            f"Peak active power         : {df['active_power_kw'].max():.2f} kW",
            f"Avg temperature           : {df['temperature_c'].mean():.1f} °C",
            f"Avg vibration             : {df['vibration_mm_s'].mean():.3f} mm/s" if "vibration_mm_s" in df.columns else "",
            f"Current SEC               : {ad.get('current_sec', 0):.4f} kWh/unit",
            f"Baseline SEC              : {ad.get('baseline_sec', 0):.4f} kWh/unit",
            f"EnPI variance             : {ad.get('enpi_variance_pct', 0):+.1f} % vs target",
        ]

        if ec:
            lines += [
                "",
                f"Estimated efficiency      : {ec.get('efficiency_pct', '—')} %",
                f"Efficiency class (illus.) : {ec.get('class_label', '—')}",
                f"  IE2 threshold ({ec.get('rating_kw','—')} kW): ≥ {ec.get('ie2_threshold','—')} %",
                f"  IE3 threshold ({ec.get('rating_kw','—')} kW): ≥ {ec.get('ie3_threshold','—')} %",
                "  (Illustrative only — not an official BEE star rating)",
            ]

        if rul.get("show_rul"):
            lines += [
                "",
                f"RUL estimate              : ~{rul['rul_hours']} h  (±{rul['ci_hours']} h)",
                "  Based on linear extrapolation of recent health trend.",
            ]

        if self.fault_diagnosis:
            lines += [
                "",
                "-" * 80,
                "SECTION 4 — FAULT DIAGNOSIS  (signature-based, simulated)",
                "-" * 80,
            ]
            for fd in self.fault_diagnosis[:3]:
                lines.append(
                    f"  {fd['fault']:20s}  {fd['likelihood']:5.1f}%  |  "
                    f"Action: {fd['action']}  |  Cost: {fd['cost_band']}"
                )

        lines += [
            "",
            "-" * 80,
            "SECTION 5 — RECOMMENDATIONS",
            "-" * 80,
            f"  Annual kWh savings (est.) : {ad.get('kwh_saved_yr', 0):,.0f} kWh",
            f"  Annual ₹ savings (est.)   : ₹{ad.get('inr_saved_yr', 0):,.0f}",
            f"  Gross Scope 2             : {ad.get('gross_scope2_kg_co2_hr', 0):.2f} kg CO2/hr",
            f"  Net Scope 2 (solar offset): {ad.get('net_scope2_kg_co2_hr', 0):.2f} kg CO2/hr",
            "",
            "-" * 80,
            "ANNEXURES",
            "-" * 80,
            "A1. ASSUMPTIONS",
            "    Grid tariff: ₹8.50/kWh | CO2 factor: 0.82 kg/kWh | 16 h/day | 300 days/year",
            "    Downtime rate: configurable in sidebar (default ₹12,000/hr)",
            "",
            "A2. STANDARDS REFERENCED",
            "    ISO 10816-3 : Mechanical vibration — evaluation of machinery vibration",
            "    IS 12615     : Energy performance of AC induction motors",
            "    IEC 60034-30-1: Efficiency classes of AC motors",
            "    BEE Guidance : Energy audit methodology",
            "",
            "A3. DATA SUMMARY",
            f"    Total rows : {len(df)} | Columns : {len(df.columns)}",
            f"    Date range : {df['timestamp'].min()} → {df['timestamp'].max()}" if "timestamp" in df.columns else "",
            "",
            "=" * 80,
            DISCLAIMER,
            "=" * 80,
        ]

        return "\n".join(lines)

    # ------------------------------------------------------------------
    # CSV export
    # ------------------------------------------------------------------
    def generate_csv_log(self) -> str:
        buf = io.StringIO()
        self.telemetry_df.to_csv(buf, index=False)
        return buf.getvalue()

    # ------------------------------------------------------------------
    # PDF export (fpdf2)
    # ------------------------------------------------------------------
    def generate_pdf(self) -> bytes:
        if not _FPDF_AVAILABLE:
            return b""

        text = self.generate_text_report()
        pdf  = FPDF()
        pdf.set_auto_page_break(auto=True, margin=15)
        pdf.add_page()

        # Title block
        pdf.set_font("Helvetica", "B", 14)
        pdf.set_fill_color(18, 26, 48)    # dark navy
        pdf.set_text_color(255, 255, 255)
        pdf.cell(0, 12, "EcoPulse — Energy & Predictive Maintenance Audit",
                 align="C", fill=True, new_x="LMARGIN", new_y="NEXT")

        pdf.set_font("Helvetica", "", 8)
        pdf.set_text_color(220, 180, 60)  # amber
        pdf.cell(0, 6, f"Generated: {self.generated_at}  |  Asset: {self.asset_name}  "
                       f"|  SIMULATED DATA — FOR DEMONSTRATION ONLY",
                 align="C", new_x="LMARGIN", new_y="NEXT")

        pdf.ln(4)
        pdf.set_text_color(30, 30, 30)
        pdf.set_font("Courier", "", 7)

        for line in text.split("\n"):
            if line.startswith("="):
                pdf.set_font("Courier", "B", 7)
                pdf.set_fill_color(230, 230, 230)
                pdf.cell(0, 4, line[:110], fill=True, new_x="LMARGIN", new_y="NEXT")
                pdf.set_font("Courier", "", 7)
            elif line.startswith("-"):
                pdf.set_font("Courier", "B", 7)
                pdf.set_fill_color(240, 240, 240)
                pdf.cell(0, 4, line[:110], fill=True, new_x="LMARGIN", new_y="NEXT")
                pdf.set_font("Courier", "", 7)
            else:
                safe = line.encode("latin-1", errors="replace").decode("latin-1")
                pdf.multi_cell(0, 4, safe[:160])

        return bytes(pdf.output())
